import { Inter } from "next/font/google";
import NotFound from "./not-found";

import "antd/dist/antd.css";
import "./globals.css";
import "@/assets/customStyle/cv.css";
import { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "hvxun's Blog",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: any) {
  return (
    <html lang={locale}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
