import { Inter } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import NotFound from "./not-found";

import "antd/dist/antd.css";
import "./globals.css";
import "@/assets/customStyle/cv.css"
import { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "vi" }];
}

export const metadata: Metadata = {
  title: "hvxun's Blog",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: any) {
  let messages;
  

  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    return <NotFound />;
  }
  

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
